name: kib_sales_force
description: "Visits Tracker for RTM Sales Force Automation"
publish_to: 'none'
version: 1.0.101+101

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  kib_debug_print: ^1.0.0
  kib_utils: ^1.0.0
  shared_preferences: ^2.5.3
  go_router: ^15.1.2
  sizer: ^3.0.5
  collection: ^1.19.1
  provider: ^6.1.5
  get_it: ^8.0.3
  equatable: ^2.0.7
  kib_flutter_utils: ^1.0.104
  uuid: ^4.5.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  envied: ^1.1.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  app_http:
    path: packages/app_http
  app_database:
    path: packages/app_database

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  built_value_generator: ^8.10.1
  envied_generator: ^1.1.1
  freezed: ^3.0.6

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/screenshots/

  # To add custom fonts to your application, add a fonts section here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
